name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
defaults:
  run:
    shell: bash
    working-directory: csharp
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: install altcover
      run: cd core/ && dotnet tool install --global altcover.visualizer --version 8.6.14
    - name: Install dependencies
      run: cd core/ && dotnet restore
    - name: Build
      run: cd core/ && dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test tests/ /p:AltCover=true
    - name: Upload code coverage report
      uses: codecov/codecov-action@v4
      with:
        flags: csharp # optional
        token: ${{ secrets.CODECOV_TOKEN }}

